# Generated by Django 4.2.2 on 2024-01-31 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Requisites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('card', 'Карта'), ('bank_account', 'Платежный счет')], max_length=20)),
                ('account_type', models.CharField(max_length=20)),
                ('owner_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('limit', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('status', models.CharField(choices=[('pending', 'Ожидает оплаты'), ('paid', 'Оплачена'), ('canceled', 'Отменена')], max_length=20)),
                ('requisites', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment_requests.requisites')),
            ],
        ),
    ]
